name : action 

on : 
  push :

jobs : 
  test-actions :
     name : test-action
     runs-on : ubuntu-latest
     steps :
       - name : list files
         run : ls
       - name: Checkout
         uses: actions/checkout@v6.0.0
       - name : ls
         run : ls      
       - name: hello-world-action
         id: hello-world-action
         uses: actions/hello-world-javascript-action@main
         with:
           who-to-greet: "Sauvik"
       - name : time
         run : echo "'Greeting time:' ${{ steps.hello-world-action.outputs.time }} "
       - name : docker action
         run : docker://hello-world:latest
 
